import { Inter } from 'next/font/google'
import '../globals.css'
import Sidebar from '../_components/Sidebar.js'
import Header from '../_components/Header.js'
import Main from '../_components/Main.js'
import CustomLayout from '../_components/CustomLayout'
import LayComp from '../_components/LayComp'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <LayComp>
          {children}
        </LayComp>
      </body>
    </html>
  )
}
