
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./_components/Sidebar.js";
import Header from "./_components/Header.js";
import Main from "./_components/Main.js";
import CustomLayout from "./_components/CustomLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <Header  />
          <div className="grid grid-cols-6 relative">
          <aside class="self-start sticky top-0 bottom-0 col-span-1">
            
        <Sidebar/>
    </aside>
            <div className="col-span-5">
              <Main>
                {children}
              </Main>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
